### ISSUE TITLE
More specific docs and/or errors

### ISSUE THREAD

**Issue by winmillwill** [slok/kube-code-generator#11]
Tried this out on cert-manager because I need to operate on certificate resources, but I can't tell whether I'm doing something wrong or if the code in their repo isn't as expected. If the tool would need some upstream change in cert-manager, then could it signal what that change would be? That way I could request that change or fork.

Here's the command and the output:
```
PROJECT_PACKAGE=github.com/jetstack/cert-manager && docker run -it --rm     -v ${PWD}:/go/src/${PROJECT_PACKAGE}    -e PROJECT_PACKAGE=${PROJECT_PACKAGE}     -e CLIENT_GENERATOR_OUT=${PROJECT_PACKAGE}/pkg/client    -e APIS_ROOT=${PROJECT_PACKAGE}/apis     -e GROUPS_VERSION="cert-manager.io:v1"     -e GENERATION_TARGETS="deepcopy,client"     quay.io/slok/kube-code-generator
go: downloading k8s.io/gengo v0.0.0-20201113003025-83324d819ded
go: downloading k8s.io/klog/v2 v2.4.0
go: downloading github.com/go-logr/logr v0.2.0
go: downloading golang.org/x/tools v0.0.0-20200616133436-c1934b75d054
go: downloading golang.org/x/mod v0.3.0
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
Generating deepcopy funcs
Generating clientset for cert-manager.io:v1 at github.com/jetstack/cert-manager/pkg/client/clientset
F0428 15:30:22.503806     452 main.go:64] Error: Failed executing generator: some packages had errors:
errors in package "github.com/jetstack/cert-manager/pkg/client/clientset/versioned":
unable to format file "/go/src/github.com/jetstack/cert-manager/pkg/client/clientset/versioned/clientset.go" (23:6: expected 'STRING', found '-' (and 1 more errors)).

errors in package "github.com/jetstack/cert-manager/pkg/client/clientset/versioned/scheme":
unable to format file "/go/src/github.com/jetstack/cert-manager/pkg/client/clientset/versioned/scheme/register.go" (23:6: expected 'STRING', found '-' (and 1 more errors)).

errors in package "github.com/jetstack/cert-manager/pkg/client/clientset/versioned/fake":
unable to format file "/go/src/github.com/jetstack/cert-manager/pkg/client/clientset/versioned/fake/clientset_generated.go" (23:10: expected 'STRING', found '-' (and 1 more errors)).
unable to format file "/go/src/github.com/jetstack/cert-manager/pkg/client/clientset/versioned/fake/register.go" (23:6: expected 'STRING', found '-' (and 1 more errors)).

goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc0001da500, 0x42b, 0x481)
	/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x9d31e0, 0xc000000003, 0x0, 0x0, 0xc0001cc380, 0x9ac195, 0x7, 0x40, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:975 +0x19b
k8s.io/klog/v2.(*loggingT).printf(0x9d31e0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x78a0b6, 0x9, 0xc000051630, 0x1, ...)
	/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:750 +0x191
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1502
main.main()
	/go/src/k8s.io/code-generator/cmd/client-gen/main.go:64 +0x58d

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x9d31e0)
	/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:417 +0xdf
```

**Comment by slok** [comment]
Hi @winmillwill!

I don't know if I'm understanding correctly the problem, I think that this is an [xy problem](https://xyproblem.info/). Could be possible that you could use the already generated stuff from cert-manager?

Some examples:

- [v1 Types](https://github.com/jetstack/cert-manager/tree/master/pkg/apis/acme/v1)
- [Certificate client](https://github.com/jetstack/cert-manager/blob/c7514d92624613395eb00da8594ffa5391a0b169/pkg/client/clientset/versioned/typed/certmanager/v1/certificate.go#L40)

I think that you could import these directly.

Does this solve your problem?

**Comment by winmillwill** [comment]
Thanks for the response, I realize now that there's no way this tool should address my problem. What I'm trying to do is handle cert-manager types, core types, and whatever types come next all with one client. Generating the client myself was the one thing I hadn't tried yet.
